"""null false for short

Revision ID: 1dd92a8b343a
Revises: 5abfcaedaf03
Create Date: 2024-03-12 08:49:01.846182

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1dd92a8b343a'
down_revision = '5abfcaedaf03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_map', schema=None) as batch_op:
        batch_op.alter_column('short',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_map', schema=None) as batch_op:
        batch_op.alter_column('short',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)

    # ### end Alembic commands ###
