"""add unique constaint to field short

Revision ID: 5abfcaedaf03
Revises: 
Create Date: 2024-03-09 10:47:46.535282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5abfcaedaf03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_map', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_url_map_short'), ['short'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_map', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_url_map_short'), type_='unique')

    # ### end Alembic commands ###
